[[profile]]
name = "Home monitor"
exec = [
  "notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"",
]
[[profile.output]]
search = "eDP-1"
enable = false
# mode = "1920x1080@144"
# position = "0,0"

[[profile.output]]
# search for a matching serial number and model by full text comparison
search = ["m=VA27EHF", "s=S6LMTF022326", "v=ASUSTek COMPUTER INC"]
enable = true
mode = "1920x1080@100.047Hz"
position = "0,0"

[[profile]]
name = "Laptop builtin"
[[profile.output]]
search = "eDP-1"
enable = true

[[profile]]
name = "Dual monitor"
[[profile.output]]
search = "n=eDP-1"
# position = "0,1440"
enable = false

[[profile.output]]
search = "n=HDMI-A-1"
# mode = "best"
position = "0,0"
mode = "2560x1440@59.95Hz"
enable = true
